const UPDATE_SELECTED_TEAM = 'UPDATE_SELECTED_TEAM'
const ADD_TEAM = 'ADD_TEAM'
const UPDATE_TEAM = 'UPDATE_TEAM'
const LOAD_TEAMS = 'LOAD_TEAMS'

export {
    UPDATE_SELECTED_TEAM,
    ADD_TEAM,
    UPDATE_TEAM,
    LOAD_TEAMS
}