const POPULATE_TEAM_FORM = 'POPULATE_TEAM_FORM'
const ADD_PLAYER = 'ADD_PLAYER'
const DELETE_PLAYER = 'DELETE_PLAYER'
const UPDATE_TEAM_DETAILS = 'UPDATE_TEAM_DETAILS'
const UPDATE_PLAYER_DETAILS = 'UPDATE_PLAYER_DETAILS'

export {
    POPULATE_TEAM_FORM,
    ADD_PLAYER,
    DELETE_PLAYER,
    UPDATE_TEAM_DETAILS,
    UPDATE_PLAYER_DETAILS
}